### ISSUE TITLE
Add delay parameter

### ISSUE THREAD

**Issue by aztecrabbit** [smacke/ffsubsync#111]
Hi,

I think the delay parameter is very useful, the synchronization result of this application is 400ms too fast. if manually, the settings are like this:

framerate from 25 -> 23.976 and delay for 800ms

**Comment by smacke** [comment]
Hi @aztecrabbit, thanks for opening an issue. The latest version of ffsubsync should now allow this with the `--apply-offset-seconds` parameter (thanks to @alucryd). You can add `--apply-offset-seconds 0.4` in your example.

You'll need to upgrade: `pip install --upgrade ffsubsync`

Will go ahead and close this; feel free to reopen if there are still issues.
