### ISSUE TITLE
Video file appears to lack subtitle stream

### ISSUE THREAD

**Issue by Rickexe** [smacke/ffsubsync#124]
Hello,

I am using the linuxserver bazarr docker image. I have subtitle synchonization turned on. No matter what I do It gives me this error. Even when using ffsubsync in custom processing. I've been on the discord servers of linuxserver and bazarr. This is a ffsubsync issue so that's why I'm posting this issue. 

I transcode my files with tdarr to remove embedded subtitles from the containers. So the mkv files contain no subtitles whatsoever. I just want to sync my external .srt files downloaded by bazarr. 

Does anyone know what this error means and how to fix it?

Thanks in advance.

![image](https://user-images.githubusercontent.com/48714886/114147727-496c5280-9919-11eb-9773-04104bff731d.png)

**Comment by smacke** [comment]
Hi @Rickexe, I see you closed this issue; were you able to resolve it? If not, could you please share the ffsubsync command that is getting invoked?

**Comment by Rickexe** [comment]
I didn't resolve the issue. I've been on this for like 12 hours now non stop. I could really use some help. I've been one 3 discord servers talking to about a 100 people.

**Comment by Rickexe** [comment]
And honestly. I still have no clue what is going wrong.

**Comment by Rickexe** [comment]
https://pastebin.com/TmyiQr52 this is my log.

**Comment by smacke** [comment]
This isn't an error; it's just an informational logging message reporting that the video doesn't include embedded subtitles (you removed them as you mentioned), so it's using the audio + detected speech as the reference against which to sync. Is the issue that the unsynced subtitles from bazarr are still out of sync?

**Comment by Rickexe** [comment]
My first message was indeed not an error. But in the logs with debug disabled it says unable to sync subtitles with every file.
also it's not writing in the ffsubsync.log file.

**Comment by Rickexe** [comment]
i am constantly getting these errors as well. 

![image](https://user-images.githubusercontent.com/48714886/114210170-bd314e00-995f-11eb-9d7b-a24480b95dbe.png)

**Comment by halali** [comment]
I think also bazarr suport ask you to enable debug for synchornization in bazarr and post it there.

**Comment by Rickexe** [comment]
no. I have been talking with bazarr support for hours. they don't know how to fix it and they tell me to go over here. this is an issue in ffsubsync.

**Comment by Rickexe** [comment]
can you guys help me? there is something wrong with ffsubsync. it's just not working.
