### ISSUE TITLE
How to use as library?

### ISSUE THREAD

**Issue by juligreen** [smacke/ffsubsync#135]
Hey :)

I'd like to use ffsubsync in another python project, since this is not documented in the README do you have a recommendation on how to use it as a library?

Thank you for any help already!

**Comment by smacke** [comment]
Hey @juligreen, it's a great question and definitely something I'd like to support better in the future. Unfortunately there's not a super clean API -- the CLI aspect is fairly entangled with the internals. The best option so far is to create a fake command line string and parse it with argparse, and then pass the args object to `ffsubsync.run`. This is what Bazarr does -- you can check out an example usage here: https://github.com/morpheus65535/bazarr/blob/ac2052f43d7e53a3bf073849e006c780a344bdbd/bazarr/subsyncer.py#L50-L56

Hope that helps and please let me know if you have any other questions!

**Comment by juligreen** [comment]
Thank you!
For now, this works well enough for me :)
