### ISSUE TITLE
--log-dir-path only used if --make-test-case set

### ISSUE THREAD

**Issue by aaronrudkin** [smacke/ffsubsync#138]
I would like to store an output log for operations; I naively assumed I could do so by throwing `--log-dir-path <dir>`, but actually this doesn't produce a log. Logs are only produced if `--make-test-case` is also included. It seems to me like while it might be true that logs should not be produced by default, it does make sense to produce them if `--log-dir-path` is provided, even if the user doesn't want to produce a test case.

**Comment by smacke** [comment]
Makes sense to me, will push a new release momentarily

**Comment by smacke** [comment]
Tested and pushed a new release, you can get the latest with `pip install --upgrade ffsubsync`

Thanks for helping to improve ffsubsync by opening an issue! Please let me know if it's still not working after the upgrade.
