### ISSUE TITLE
[FR] Make `reference` optional when `--apply-offset-seconds` is used

### ISSUE THREAD

**Issue by NightMachinary** [smacke/ffsubsync#140]
This way we can use `ffsubsync` to just apply a known delay to subtitle files.

**Comment by smacke** [comment]
This is a good idea. Should be fixed in d98dfe2; will close this issue once I get a release out.

**Comment by smacke** [comment]
I just pushed a new release so will go ahead and close out this issue. You should be able to use the new behavior after running
```
pip install --upgrade ffsubsync
```

Please don't hesitate to reopen if you encounter any problems.
