### ISSUE TITLE
future-annotations broken

### ISSUE THREAD

**Issue by francogrex** [smacke/ffsubsync#143]
python2 and 3
Could not find a version that satisfies the requirement future-annotations (from ffsubsync) (from versions: )
No matching distribution found for future-annotations (from ffsubsync)

**Comment by smacke** [comment]
Hi there! ffsubsync doesn't support python 2 or python 3 < 3.6. What version of python 3 were you using?

Also, sounds like it could potentially be an issue with your version of pip -- consider trying `python -m pip install --upgrade pip`

**Comment by francogrex** [comment]
Python-3.6.9

**Comment by smacke** [comment]
That's weird. What do you get when you run `pip install future-annotations`?

**Comment by formlessdao** [comment]
> That's weird. What do you get when you run `pip install future-annotations`?

Hi, can you tell me please how can I make your app work for my case? I have transcribed a video in Word and now basically I have a .doc file with the full transcript. How can I use it with your app to generate a SRT formatted fie with the correct timings?

**Comment by smacke** [comment]
> > That's weird. What do you get when you run `pip install future-annotations`?
> 
> Hi, can you tell me please how can I make your app work for my case? I have transcribed a video in Word and now basically I have a .doc file with the full transcript. How can I use it with your app to generate a SRT formatted file with the correct timings?

That's not a use case ffsubsync supports. ffsubsync is about taking an existing srt with (possibly out-of-sync) timestamps and synchronizing said timestamps to the video. In your case, it sounds like you don't have existing timestamps yet, so you're better off trying software specialized for video transcription.

PS -- just a suggestion for github etiquette @formlessdao, please try to stay on topic for whatever issue is being discussed in the current thread; e.g. your question could have been posted as a new issue rather than piggy-backing off of an existing one.

**Comment by francogrex** [comment]
Hi installed python 3.7.4 and now all is fine ffsubsync works as expected. I think the problem is that 3.6.5 is no good anymore because of broken dependencies, to your question: pip install future-annotations on 3.6.5 results in error (another missing library), installing from whl also fails. Again, >= 3.7 seems good if you'd like to update the documentations.

**Comment by smacke** [comment]
> Hi installed python 3.7.4 and now all is fine ffsubsync works as expected. I think the problem is that 3.6.5 is no good anymore because of broken dependencies, to your question: pip install future-annotations on 3.6.5 results in error (another missing library), installing from whl also fails. Again, >= 3.7 seems good if you'd like to update the documentations.

That's great to hear! Mind posting the output of `pip install future-annotations` you got on 3.6? I try to support 3.6 as well -- according to CI, it should be working, so not sure what happened.

**Comment by smacke** [comment]
The newest version (grab with `pip install --upgrade ffsubsync`) no longer depends on future-annotations, so I'll go ahead and close out this issue.
