### ISSUE TITLE
Broken submodule

### ISSUE THREAD

**Issue by yurivict** [smacke/ffsubsync#163]
Submodule https://github.com/smacke/subsync-data/tree/cb3c89741db871d095d4da067a065bcf0821f1c6 is a broken URL.

**Comment by smacke** [comment]
Hi, subsync-data is a private repository with test data. It's not meant to be accessible by people other than me.

**Comment by fcakyon** [comment]
@smacke repo is not installable by `pip install git+https://github.com/smacke/ffsubsync` due to that broken submodule. How to handle it?

**Comment by smacke** [comment]
Hi @fcakyon in the future please open an issue for that, since the thing we want to support (pip install from github) is not necessarily related to the test data submodule.

For that, as described in the readme, you can use the `latest` branch, which has the submodule removed:

```
pip install git+https://github.com/smacke/ffsubsync@latest
```

**Comment by fcakyon** [comment]
Thank you @smacke 🙏
