### ISSUE TITLE
If there is some sort of api or a way to send arguments directly I will create a GUI for Mac/Linux/Windows for users

### ISSUE THREAD

**Issue by jlw4049** [smacke/ffsubsync#165]
If there is a way to send args in python or to use this as a package, I don't mind creating a GUI in tkinter that takes advantage of this.

**Comment by MinmoTech** [comment]
See https://github.com/smacke/ffsubsync/issues/135

**Comment by jlw4049** [comment]
Hmm, I suppose I can start on this in the near future then. I'll book mark this.

**Comment by MinmoTech** [comment]
Depending on your use-case, the [Migaku-Subtitle-Syncer](https://github.com/migaku-official/migaku-subtitle-syncer/) is a simple gui for ffsubsync
