### ISSUE TITLE
cchardet no longer updated

### ISSUE THREAD

**Issue by vevv** [smacke/ffsubsync#166]
cchardet, a dependency of ffsubsync is no longer supported, and will not build correctly on Python 3.11 on Windows 10.
See: https://github.com/PyYoshi/cChardet/issues/77

[charset_normalizer](https://github.com/Ousret/charset_normalizer) seems like a decent drop-in replacement others suggest

**Comment by DoTheEvo** [comment]
So what can I do to get `pip install ffsubsync` working?

**Comment by smacke** [comment]
Thanks for flagging. I took a look at charset_normalizer and it seems like a good stopgap for now for later versions of Python. Unfortunately it seems to have some gaps when compared with cchardet, e.g. for detecting more obscure encodings such as BIG5. Anyway the next release will prefer charset_normalizer over cchardet on Windows + Python 3.11.

**Comment by reliant8307** [comment]
> Thanks for flagging. I took a look at charset_normalizer and it seems like a good stopgap for now for later versions of Python. Unfortunately it seems to have some gaps when compared with cchardet, e.g. for detecting more obscure encodings such as BIG5. Anyway the next release will prefer charset_normalizer over cchardet on Windows + Python 3.11.

I'm getting the same issue using Linux when trying to build 0.4.21 version (cchardet won't build because it can't find longintrepr.h when using Python 3.11). Could you apply this change to Linux too?

I commented out the requirements.txt  line from git and it's working fine here:

#cchardet;platform_system!='Windows'

Thanks!

**Comment by smacke** [comment]
@reliant8307 thanks for raising -- just pushed a new version that fixes this. For some reason I thought it was only Windows that had issues with cchardet on Python 3.11, but looks like it's all OSes.

**Comment by StayBlue** [comment]
Instead of using cchardet, it's possible to just use [faust-cchardet](https://github.com/faust-streaming/cChardet), a maintained version of cchardet.

**Comment by smacke** [comment]
Thanks for the pointer! I've deployed an update to use faust-cchardet in the latest version of ffsubsync.
