### ISSUE TITLE
OSS License compatibility question

### ISSUE THREAD

**Issue by Ashley123456789** [smacke/ffsubsync#173]
There’s possible confusion on the license of your repository when you combine other open-source code. 

The module `ffsubsync/sklearn_shim.py` claims its license as **the BSD license**. 
However, the license of your whole project is shown as **the MIT license** in LICENSE, i.e., **less strict** than the BSD license on license terms, which may impact the whole license compatibility in your repository, thus confusing subsequent users and bringing possible legal and financial risks.

If possible, you can fix them in one of the following ways:

- select another proper license for your repository, e.g., BSD-3-clause, Apache-2.0
- update this license with term exceptions added for specific modules
- remove these modules if they are not actually useful

**Comment by smacke** [comment]
Thanks for the concern; not a legal expert but to the best of my knowledge I can include BSD3-licensed code in other projects provided the copyright notice and disclaimers are included. To be safe I went ahead and copied these inline in sklearn_shim.py which is the only file that uses borrowed code, so I think it should be OK.
