### ISSUE TITLE
Why do I skip some subtitles, please help me

### ISSUE THREAD

**Issue by yuwei1234** [smacke/ffsubsync#195]
Why do I skip some subtitles, it causes me to miss some subtitles

![image](https://github.com/user-attachments/assets/8845096e-e8f5-4bda-afd3-99fa443a2587)

![image](https://github.com/user-attachments/assets/447f4b53-9e55-458a-b54d-08a6629269d8)

![image](https://github.com/user-attachments/assets/5046c1b2-a512-44fa-9732-db9a99b108eb)

**Comment by yuwei1234** [comment]
please help me

**Comment by smacke** [comment]
@yuwei1234 are the rest of the subtitles in sync or no? I assume not if these ones are supposed to appear?

**Comment by smacke** [comment]
You might try passing `--no-fix-framerate` in case the subtitle time range is getting stretched and causing it to go out of bounds.

**Comment by smacke** [comment]
@yuwei1234 你已经试一试把 `--no-fix-framerate` pass in 吗？

**Comment by yuwei1234** [comment]
> @yuwei1234 你已经试一试把 pass in 吗？`--no-fix-framerate`

--max-offset-seconds=0.5      I  use this can  solve this problem

**Comment by yuwei1234** [comment]
> @yuwei1234 你已经试一试把 `--no-fix-framerate` pass in 吗？

I will  try it
