### ISSUE TITLE
won't work

### ISSUE THREAD

**Issue by raphael12333** [smacke/ffsubsync#199]
![fkit](https://github.com/user-attachments/assets/0e6d7a1d-a39e-4b96-b5c8-c8db282f2d9c)

...

**Comment by smacke** [comment]
I'm afraid a truncated stack trace isn't enough to diagnose what's going on. Feel free to reopen if you can provide more info. Based on what's present ("The system cannot find the file"), the first thing is to make sure that the paths to the files are specified correctly.

**Comment by raphael12333** [comment]
![Screenshot 2024-12-25 at 10 40 27 PM](https://github.com/user-attachments/assets/bea3e514-493c-4374-8f4d-348e58d317a4)
