### ISSUE TITLE
New name / name for PyPI

### ISSUE THREAD

**Issue by smacke** [smacke/ffsubsync#55]
I should have registered this software on PyPI a long time ago, but sadly [there's another 'subsync' package already registered](https://pypi.org/project/subsync/) (courtesy of @tympanix :) for which the name collision has occasionally resulted in confusion. And in general, the installation command for this project, `pip install git+https://github.com/smacke/subsync@STABLE`, is super clunky.

As such, this project needs a new name. Here are ideas floating through my head, none of which I particularly like:
- subsume (reserved this name on PyPI a while back but having second thoughts now)
- capsync
- subtools (emphasizes other tools besides syncing, since we can support merging, manual shifting, reencoding, and possibly other transformations)
- subtitle-tools
- subsed ("subtitle stream editor", again going with philosophy of a more swiss army knife-style tool)
- subcat ("cat" but for subtitles, again going with swiss army knife philosophy)
- subsyncer
- subtitle-sync
- subtitle-syncer
- subalign
- syncsubs
- subsink
- sublingo (emphasizes the language-agnostic features, e.g. audio + text in different languages, automatic character encoding detection, ability to merge different files into bilingual subtitles, etc)
- sublimate
- substantial
- subconvolve (since we use FFT; although `srtsync` does too)
- sublink (I like this one the most currently: this tool "links subtitles and video" and does so in the "blink" of an eye.)
- subconnect

For anyone reading this, please feel free to weigh in with thoughts, votes, or other suggestions! I recommend using https://pypi.org/ to check if a particular idea already exists.

Please stay safe and healthy!

Stephen

**Comment by juligreen** [comment]
Since this is a _relatively_ niche product, i think a self-explanatory name would be best.
Also, syncing subtitles is it's key feature, which should be highlighted by the title.

I vote for either:

- subsyncer
- subtitle-sync
- subtitle-syncer
- subalign
- sublink

**Comment by smacke** [comment]
After a long deliberation, I ended up going with ffsubsync, as both an homage to ffmpeg and because of the use of FFT for the sync algorithm. We are now [ffsubsync](https://pypi.org/project/ffsubsync/) on pypi!
