### ISSUE TITLE
bazarr integration

### ISSUE THREAD

**Issue by rigas40** [smacke/ffsubsync#65]
is possible integrate subsync in bazarr in windows 7 ?

**Comment by jobrien2001** [comment]
run it as a post processing script in bazarr

**Comment by rigas40** [comment]
wht is command for windows?

**Comment by jobrien2001** [comment]
i dont use windows for this but its the same one you are using currently.

c:/mypath/subsync.exe myoptions

check bazaar post processing it will give you the variable names you need.

**Comment by nikolicjakov** [comment]
If you are using docker there is image that you could use for this.
On this link https://forum.djdev.org/showthread.php?p=3#post3

**Comment by babos123** [comment]
> If you are using docker there is image that you could use for this.
> On this link https://forum.djdev.org/showthread.php?p=3#post3

I tried throught portainer to change image but it say "no such image".

**Comment by nikolicjakov** [comment]
@babos123 Are you sure that you have selected custom repository not dockerhub in your portainer.

If you want to use this image you will need to configure portainer to user 3rd-party repository "repo.djdev.org"

**Comment by babos123** [comment]
Working now thanks!

**Comment by morpheus65535** [comment]
FYI I'm looking at integrating this directly into Bazarr.

**Comment by nikolicjakov** [comment]
@morpheus65535 That would be great.

**Comment by pablo3x6** [comment]
> > @morpheus65535 May i ask which version of subsync will be used? there are 2 named the same with 2 different approaches to sync subs and both are quite successful. Or will be it be an option to choose?
> 
> We'll be using ffsubsync by @smacke

How is the integration coming along?

**Comment by morpheus65535** [comment]
> > > @morpheus65535 May i ask which version of subsync will be used? there are 2 named the same with 2 different approaches to sync subs and both are quite successful. Or will be it be an option to choose?
> > 
> > 
> > We'll be using ffsubsync by @smacke
> 
> How is the integration coming along?

Been there for more than a year...

**Comment by pablo3x6** [comment]
> > > > @morpheus65535 May i ask which version of subsync will be used? there are 2 named the same with 2 different approaches to sync subs and both are quite successful. Or will be it be an option to choose?
> > > 
> > > 
> > > We'll be using ffsubsync by @smacke
> > 
> > 
> > How is the integration coming along?
> 
> Been there for more than a year...

Right, sorry, the Sync button in Tools. Tried but it didn't work for my series. Sorry for the confusion, I'll check out the logs

**Comment by smacke** [comment]
Will go ahead and close this issue to avoid further confusion -- thanks again @morpheus65535 for working on the integration!
