### ISSUE TITLE
Installing ffsubsync from pip errors due to HISTORY.rst

### ISSUE THREAD

**Issue by obroomhall** [smacke/ffsubsync#73]
**Environment (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - python version: 3.6.9
 - subsync version: ffsubsync-0.3.4

**Describe the bug**
$ pip install ffsubsync
Collecting ffsubsync
  Downloading ffsubsync-0.3.4.tar.gz (16 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/oliver/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-tp10via_/ffsubsync/setup.py'"'"'; __file__='"'"'/tmp/pip-install-tp10via_/ffsubsync/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-fii55wuv
         cwd: /tmp/pip-install-tp10via_/ffsubsync/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-tp10via_/ffsubsync/setup.py", line 13, in <module>
        history = read_file('HISTORY.rst')
      File "/tmp/pip-install-tp10via_/ffsubsync/setup.py", line 9, in read_file
        with open(fname, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'HISTORY.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**To Reproduce**
$ pip install ffsubsync

**Comment by smacke** [comment]
@obroomhall Thank you for catching, this should now be fixed:
`pip install --upgrade --no-cache-dir ffsubsync`
