### ISSUE TITLE
[Feature Request] Allow to use subtitles as a reference

### ISSUE THREAD

**Issue by sevospl** [smacke/ffsubsync#89]
Since Bazarr uses ffsubsync for syncing, I thought it might be convenient to use already synced subtitles as a reference for another language.

Example:
1. There's no English subtitles - let's download it.
2. ffsubsync extracts audio track from a video (if there's no embedded subs) and shifts the downloaded subtitles.
3. There's also German subtitles - Bazarr executes syncing it but then using English subtitles that are already synced as a reference.

This way we end up being able to sync more languages instantly.

**Comment by morpheus65535** [comment]
I agree that using external subtitles as reference could be a nice idea!

**Comment by sevospl** [comment]
Looks like there's a [commit](https://github.com/smacke/ffsubsync/commit/558bc6dc1d5342d4a5910166cf12ebb5890e86b7) related to my request, as well covered in the [README](https://github.com/smacke/ffsubsync#usage). I have already tested it and it works perfectly.

Thanks for the feature! I'm closing the issue as it's solved :)
