### ISSUE TITLE
Once synced, .ass subtitles no longer have fonts/styles

### ISSUE THREAD

**Issue by sevospl** [smacke/ffsubsync#90]
Usually, when syncing subtitles for anime, fonts / styles don't remain once synced. ffsubsync is supposed to leave it as is instead of removing/not preserving it. I hope it can be fixed.

Edit: Sorry for the wrong label, I hope you (smacke) don't get mad :)

**Comment by smacke** [comment]
@sevospl thanks for catching this -- unfortunately this is going to be in the backlog for a while but I'll try to get to it at some point.

**Comment by lleaff** [comment]
This is a total hack but in the meantime, I run this [script](https://gist.github.com/lleaff/267c0e4617ff391fefe10bc6afebde0b) (`transfer-ass-headers old.srt synced.srt`) after invoking subsync on .ass files.

**Comment by smacke** [comment]
Thanks @alucryd for taking this on!
