### ISSUE TITLE
--make-test-case cannot work on Windows

### ISSUE THREAD

**Issue by morpheus65535** [smacke/ffsubsync#92]
You're trying to create a directory with colons in it's name. This is not possible under Windows OS.

https://github.com/smacke/ffsubsync/blob/master/ffsubsync/ffsubsync.py#L42-L45

**Comment by morpheus65535** [comment]
Ive replaced colons in hour with dash and it works perfectly fine. Would it be possible to remove the empty directory once the tar.gz file is created?

**Comment by smacke** [comment]
Hi @morpheus65535, thanks for catching this. By remove the empty directory, are you referring to `tar_dir` in the linked code? I thought it should get removed here: https://github.com/smacke/ffsubsync/blob/997749de8aac74ec19137a2e641b97ef1bba81ea/ffsubsync/ffsubsync.py#L71

**Comment by morpheus65535** [comment]
It never get there in my case... is that properly indented?

https://github.com/smacke/ffsubsync/blob/997749de8aac74ec19137a2e641b97ef1bba81ea/ffsubsync/ffsubsync.py#L65-L68

**Comment by morpheus65535** [comment]
Fixed by #97

**Comment by smacke** [comment]
Thank you!
