### ISSUE TITLE
There has been an error in the syncing process

### ISSUE THREAD

**Issue by maxtheking** [smacke/ffsubsync#99]
[FAILED.txt](https://github.com/smacke/ffsubsync/files/5124843/FAILED.txt)

**Additional context**
Using the script rsubsync.py to sync all subtitles in a folder. Most files get synced properly, but every few episodes a error seems to pop up.
[Screenshot](https://i.maxkoning.nl/2020-08-25_17-53-23.jpg)

Any ideas? Is this just because i'm syncing too many subtitles?

**Comment by maxtheking** [comment]
UPDATE: [Syncing movies results in even more errors...](https://i.maxkoning.nl/2020-08-26_11-54-40.jpg)

**Comment by smacke** [comment]
@maxtheking thanks for filing an issue and sorry the sync failed sometimes. One of the most common errors is when the SRT parsing library doesn't work on some malformed SRT file, which appears to be the case in the `FAILED.txt` attachment. Would you be willing to attach the unsynced srt associated with this case? If so I can then take a look and see what's going on.

**Comment by maxtheking** [comment]
@smacke Thanks! I have attached the unsynced failing SRT file below.

**Comment by smacke** [comment]
@maxtheking I think that file is different from the one in the `FAILED.txt` attachment. It seems the srt parsing library doesn't have any issues with this one. Does it fail sync as well?

If you attach the one from `FAILED.txt` I can look into why the parser is having trouble with that one.

**Comment by maxtheking** [comment]
@smacke Sorry, my b
[Fear.the.Walking.Dead.S05E10.1080p.WEB.h264-TBS[rarbg].nl.zip](https://github.com/smacke/ffsubsync/files/5132968/Fear.the.Walking.Dead.S05E10.1080p.WEB.h264-TBS.rarbg.nl.zip)
ad. The correct file is attached below.

**Comment by smacke** [comment]
@maxtheking I took a look and it seems that the very last subtitle in that file only has a timestamp but no text, and the srt library doesn't like this. You can delete that last subtitle and it should not have the same error any more. I will see if there's a way to increase tolerance of srt on my end before pestering @cdown to see if he'd be willing to add a feature.

This is unfortunately just one kind of error that can occur; for other errors, I'd be happy to take a look, I just ask that you please file separate issues for each one and attach the tarball created from the `--make-test-case` flag of ffsubsync.

**Comment by cdown** [comment]
Thanks, let me take a look. Sounds simple enough to support.

**Comment by maxtheking** [comment]
@smacke Thanks for looking into it! So does it not complete at all when it encounters an error? Or does it just continue the sync and ignore the part that results in errors?

**Comment by cdown** [comment]
Oh, the real problem is not only that it doesn't have any content, but that it also doesn't have any final EOL.

**Comment by cdown** [comment]
As of https://github.com/cdown/srt/commit/11089f1e021f2e074d04c33fc7ffc4b7b52e7045, we now support this. I'll release a new srt with it in in the coming days. :-)

Thanks for the example!

**Comment by smacke** [comment]
Wow! Very fast turnaround, thank you @cdown!

**Comment by cdown** [comment]
srt 3.4.1 released. :-)

**Comment by maxtheking** [comment]
Awesome! Thanks a lot to both of you, excellent support!
